version: '3.9'

services:
  db:
    image: postgis/postgis:13-3.1
    environment:
      POSTGRES_DB: marchan_database
      POSTGRES_USER: votana
      POSTGRES_PASSWORD: votana
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: